apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apim-marketplace-examples
  description: "Mock server that pulls published API specifications and exposes their examples"
  annotations:
    jenkins.io/job-full-name: "cft:HMCTS_j_to_z/service-api-marketplace-examples"
    github.com/project-slug: 'hmcts/service-api-marketplace-examples'
  tags:
    - java
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=api-marketplace-tech
      title: "#api-marketplace-tech on Slack"
      icon: chat
spec:
  type: service
  system: apim
  lifecycle: experimental
  owner: group:dts-api-marketplace
