apiVersion: v2
appVersion: "1.0"
description: A Helm chart for the API Marketplace Examples mock server
name: apim-marketplace-examples
home: https://github.com/hmcts/service-api-marketplace-examples
version: 0.0.2
maintainers:
  - name: HMCTS API Marketplace team
dependencies:
  - name: java
    version: 5.3.1
    repository: 'oci://hmctspublic.azurecr.io/helm'
