java:
  replicas: 1
  applicationPort: 8081
  image: 'hmctsprod.azurecr.io/apim/marketplace-examples:latest'
  ingressHost: apim-marketplace-examples-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  environment:
    APPLICATIONINSIGHTS_ENABLED: "false"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=00000000-0000-0000-0000-000000000000"
