server:
  port: 8081
  shutdown: "graceful"

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.apim.controllers
  writer-with-order-by-keys: true

spring:
  application:
    name: API Marketplace Examples

marketplace:
  specs:
    - code: hrds
      name: Hearing Results Document Subscription
      url: https://raw.githubusercontent.com/hmcts/api-cp-crime-hearing-results-document-subscription/main/src/main/resources/openapi/openapi-spec.yml
